// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yktjcooctsvsmztwkpfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrdGpjb29jdHN2c216dHdrcGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM4MjI3NzYsImV4cCI6MjA5OTM5ODc3Nn0.E3LEzgjJMVGpU6IIKr0K9kUZsF-iZUOl-phx4YvDqWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});